version: '2'
services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ${VOLUME_PATH}/db/mysql:/var/lib/mysql
      - ./mysql:/data:ro
    command: --init-file /data/${MYSQL_INIT_FILE}
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    expose:
      - "3306"
    networks:
      - vigilo
  web:
     image: tutum/apache-php
     port:
       - "80"
     links:
       - db
     volumes:
       - ./app:/app
       - ${VOLUME_PATH}/files/caches:/app/caches
       - ${VOLUME_PATH}/files/maps:/app/maps
       - ${VOLUME_PATH}/files/images:/app/images
     environment:
       - MYSQL_USER
       - MYSQL_PASSWORD
       - MYSQL_DATABASE
       - MYSQL_HOST
       - MAPQUEST_API
       - TWITTER_CONSUMER
       - TWITTER_CONSUMERSECRET
       - TWITTER_ACCESSTOKEN
       - TWITTER_ACCESSTOKENSECRET
     networks:
       - vigilo
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
          PMA_HOST: db
      links:
        - db
      ports:
        - "8888"
      networks:
        - vigilo
networks:
  vigilo:
    internal: true


