version: '2'
services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ${VOLUME_PATH}/db/mysql:/var/lib/mysql
      - ./mysql:/data:ro
    command: --init-file /data/${MYSQL_INIT_FILE}
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    expose:
      - "3306"
  web:
     image: badele/vigilo-backend
     expose:
       - "80"
     links:
       - db
     volumes:
       - ./app:${ROOT_APP_DIR}
       - ${VOLUME_PATH}/files/caches:${ROOT_APP_DIR}/caches
       - ${VOLUME_PATH}/files/maps:${ROOT_APP_DIR}/maps
       - ${VOLUME_PATH}/files/images:${ROOT_APP_DIR}/images
       - ${VOLUME_PATH}/logs/apache2/var_log_apache2:/var/log/apache2
    environment:
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE

