db:
  image: mariadb
  restart: always
  volumes:
    - /data/docker/jsudd/mysql:/var/lib/mysql
    - ./mysql:/data:ro
  command: --init-file /data/${MYSQL_INIT_FILE}
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: username
    MYSQL_PASSWORD: passwd
    MYSQL_DATABASE: dbname
  ports:
    - "3306:3306"

web:
   image: tutum/apache-php
   environment:
     MAPQUEST_API: ${MAPQUEST_API}
   ports:
     - "80:80"
   links:
     - db
   volumes:
     - ./app:/app

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
        PMA_HOST: db    
    links:
        - db
    ports:
        - "8888:80"    