version: '2'
services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ${VOLUME_PATH}/db/mysql:/var/lib/mysql
      - ./mysql/sql_migration.sql:/docker-entrypoint-initdb.d/sql_migration.sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    ports:
      - "3306:3306"
    #networks:
      #- vigilo
  web:
     image: badele/vigilo-backend
     ports:
       - "80:80"
     links:
       - db
     volumes:
       - ./app:${ROOT_APP_DIR}
       - ./app/config/config_dev.php:${ROOT_APP_DIR}/config/config.php
       - ${VOLUME_PATH}/files/caches:${ROOT_APP_DIR}/caches
       - ${VOLUME_PATH}/files/maps:${ROOT_APP_DIR}/maps
       - ${VOLUME_PATH}/files/images:${ROOT_APP_DIR}/images
     environment:
       - ENV 
     #networks:
       #- vigilo
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
          PMA_HOST: db
      links:
        - db
      ports:
        - "8888:80"
  netdata:
      image: netdata/netdata
      hostname: vigilo.org
      environment:
          PGID: ${DOCKER_GROUP_ID}
      ports:
        - 19999:19999
      cap_add:
        - SYS_PTRACE
      security_opt:
        - apparmor:unconfined
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro