version: '3.7'
services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ${VOLUME_PATH}/db/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
  web:
     image: vigilobs/vigilo-backend:0.0.18
     working_dir: /var/www/html
     ports:
       - "${BIND}:80"
     links:
       - db
     volumes:
       - ${VOLUME_PATH}/files/caches:/var/www/html/caches
       - ${VOLUME_PATH}/files/maps:/var/www/html/maps
       - ${VOLUME_PATH}/files/images:/var/www/html/images
       - ${VOLUME_PATH}/logs/apache2/var_log_apache2:/var/log/apache2
     environment:
       - MYSQL_HOST
       - MYSQL_USER
       - MYSQL_PASSWORD
       - MYSQL_DATABASE
  backup:
    build: docker_backup/
    volumes:
      - ${VOLUME_PATH}/backup:/backup
      - ${VOLUME_PATH}/files/caches:/tosave/caches:ro
      - ${VOLUME_PATH}/files/maps:/tosave/maps:ro
      - ${VOLUME_PATH}/files/images:/tosave/images:ro
      - ${VOLUME_PATH}/logs/apache2/var_log_apache2:/tosave/logs:ro
    environment:
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - AUTOUPDATE

